### ISSUE TITLE
webui with an IP other than localhost

### ISSUE THREAD

**Issue by rezad1393** [bitmagnet-io/bitmagnet#113]
**Have you checked the roadmap on the website, and existing issues, before opening a dupllcate issue?**
Yes

**Is your feature request related to a problem? Please describe.**
I want to run the docker container on a 24/7 on a LAN connected client that is headless. and then use http to use webui on laptop when I need it.

**Describe the solution you'd like**
allow assigning a non-localhost ip

**Describe alternatives you've considered**
using proxies (like stunnel) to redirect it. works but it is dirty 

update:
after using stunnel I see that this webui listens at  listen tcp4 0.0.0.0:3333 which works for me but it is better to be able to separate the webui ip (like 127.0.0.1 and lan ip and so on)

**Comment by mgdigital** [comment]
Hi, you could run the Angular app standalone with a custom environment file pointing to any address (see this file that I use for local development: https://github.com/bitmagnet-io/bitmagnet/blob/main/webui/src/environments/environment.ts), however the main server would still need to be running at an address that's accessible by your web browser, so I don't think I understand what this would achieve...

**Comment by rezad1393** [comment]
I not pro enough to try that (or even understand it to use it) but because as I added to the post I can use the 0.0.0.0:3333 on lan so it is ok.
