### ISSUE TITLE
allow configured threshold for files in a torrent

### ISSUE THREAD

**Issue by rezad1393** [bitmagnet-io/bitmagnet#115]
**Have you checked the roadmap on the website, and existing issues, before opening a dupllcate issue?**
Yes

**Is your feature request related to a problem? Please describe.**
when I get a big torrent with lots of files I get this:
"Files information was not saved as the number of files is over the configured threshold. "

**Describe the solution you'd like**
allow uesrs to change this threshold.

**Describe alternatives you've considered**
nothing?

**Additional context**
is this because the app tries to limit size of db?
if this is changed then torrents got before, get updated with new info of files?

btw if I delete a torrent from list, does it get added back to db after app restart?
or is it forever gone?

**Comment by mgdigital** [comment]
> allow uesrs to change this threshold.

This is already configurable, please refer to the documentation: https://bitmagnet.io/setup/configuration.html

> is this because the app tries to limit size of db?

Yes

> if this is changed then torrents got before, get updated with new info of files?

At the moment, no. There may be a solution in future.

> btw if I delete a torrent from list, does it get added back to db after app restart? or is it forever gone?

It's gone until the crawler finds it again. See the comment here for further technical details: https://github.com/bitmagnet-io/bitmagnet/issues/70#issuecomment-1832682032
