### ISSUE TITLE
Filter by detected unicode script types or IANA character sets detected in name and files.path values

### ISSUE THREAD

**Issue by bmfrosty** [bitmagnet-io/bitmagnet#155]
### Is your feature request related to a problem? Please describe

I'd like to be able to filter for types of script or IANA character set detected in file and path names.

### Describe the solution you'd like

Unicode is broken up into multiple script types and character sets (I believe there are characters than can be a part of multiple script types or character sets, but I am not a unicode expert).  I would like to be able to filter by things that only include things in something like Latin script or the US-ASCII character set to try and limit one way, or alternatively search for things that include Hiragana OR Katakana, or even more complex like Hiragana OR Katakana.  Even more complex would be Han AND NOT Hiragana AND NOT Katakana.

### Additional context

Certain languages will include characters in multiple scripts or character sets.  For content in English, it may work well to filter only by something (this will take trial and error), but Chinese content will contain Han, but not Hiragana or Katakana, and Japanese content will usually contain Hiragana or Katakana and also other characters.

**Comment by mgdigital** [comment]
Hi @bmfrosty , there's already this open issue that might do what you want in a slightly different way - https://github.com/bitmagnet-io/bitmagnet/issues/49 - if the language filter was populated using the results from https://github.com/pemistahl/lingua-go, would this achieve what you'e aiming for?
