### ISSUE TITLE
A lot of TMDB API requests when the API key is invalid

### ISSUE THREAD

**Issue by ioqy** [bitmagnet-io/bitmagnet#157]
- [x] I have checked the existing issues to avoid duplicates
- [x] I have redacted any info hashes and content metadata from any logs or screenshots attached to this issue

### Describe the bug

Bitmagnet will continue to make TMDB API requests with an invalid API key at a rather high rate.

In 60 seconds with an invalid API key, bitmagnet made 700 requests.

### To Reproduce

1. Set a wrong API key
2. Start bitmagnet
3. See a lot of "Invalid API key: You must be granted a valid key." messages in the log

### Expected behavior

Either stop or severely limit the TMDB API requests when the API key is invalid.

### Environment Information (Required)

- Bitmagnet version: 0.7.3

**Comment by mgdigital** [comment]
It should arguably halt the application if it's invalid, as the classifier wouldn't be able to function and you might not notice without looking at the logs. Also possibly an idea to have an option to disable TMDB matching altogether. 

Slightly aside, I want to replace the TMDB client library in use as it doesn't use the Go `context` convention and patches its own timeout onto requests (especially problematic with rate limiting), which I've in turn had to hack around to fix....

**Comment by ioqy** [comment]
I don't know if this is possible, but could the API key become invalid while bitmagnet is already running? Then a check at the start of bitmagnet might not be enough.

Another possibility is that the API key could fallback to the built in key. This would be the least disruptive to the operation of the application.

**Comment by mgdigital** [comment]
> the API key could fallback to the built in key

Right yes, that's obviously what should happen, thanks! I'm going to do this as part of replacing the TMDB client....

> could the API key become invalid while bitmagnet is already running? 

It's certainly possible but probably a rare enough edge case that we don't need to handle it in any other way than letting it fail?

**Comment by ioqy** [comment]
> It's certainly possible but probably a rare enough edge case that we don't need to handle it in any other way than letting it fail?

Just letting it fail would flood the API with unnecessary requests. Even if it is just an edge case.
I would prefer the fallback to the built in key any time the API key is invalid. And not just a single validity check of the API key at the application startup.

**Comment by mgdigital** [comment]
To fall back to the default key while mid-flow would involve re-instantiating the whole client, and patching it into anything that's using the client (as rate limit for the built-in key is fixed at 1 second, so you'd also need a new rate limiter instance). So it would add significant complexity for the sake of an edge case. As a compromise, when it fails auth (having previously succeeded) I'll make it fail every subsequent request without calling TMDB, which will avoid flooding the API.

**Comment by mgdigital** [comment]
As a compromise I'll stop it making further requests once it gets a 401. To fall back mid-flow involves resetting the rate limit too, and it's adding too much complexity for the sake of an edge case.
