### ISSUE TITLE
Docker compose web interface doesn't work

### ISSUE THREAD

**Issue by ggeorgovassilis** [bitmagnet-io/bitmagnet#19]
I ran bitmagnet following the docker compose instructions from [1] using v0.0.4. System specs: Ubuntu 22.04 6.2.0-34-generic on AMD64.

The web interface at http://localhost:3333 immediately disconnects the network connection:

```
* Trying 127.0.0.1:3333...
* Connected to localhost (127.0.0.1) port 3333 (#0)
> GET / HTTP/1.1
> Host: localhost:3333
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```
I'm attaching docker compose console logs [2].

[1] https://bitmagnet.io/setup/installation.html 
[2] [logs.txt](https://github.com/bitmagnet-io/bitmagnet/files/12826186/logs.txt)

**Comment by mgdigital** [comment]
I'm not having this issue and others are running this successfully. Your logs suggest memory related issues. Maybe try on a different machine?
