### ISSUE TITLE
How to install bitmagnet with docker? 

### ISSUE THREAD

**Issue by VanTuz5** [bitmagnet-io/bitmagnet#204]
I'm sorry for the stupid question. I want to install the program using docker, but I have no idea how to do it. The website says - here's the code for you, run it through docker. Where and how should it be placed? I have the docker installed.

**Comment by VanTuz5** [comment]
I'm not asking you to teach me from scratch, I'm asking you to explain how to install your program.

**Comment by NiklasBr** [comment]
1. Install Docker (you have done this already)
2. Follow [this page in the documentation](https://bitmagnet.io/setup/installation.html), it says:
   > The quickest way to get up-and-running with bitmagnet is with [Docker Compose](https://docs.docker.com/compose/). The following docker-compose.yml is a minimal example. For a more full-featured example including VPN routing and observability services see the [docker compose configuration in the GitHub repository](https://github.com/bitmagnet-io/bitmagnet/blob/main/docker-compose.yml).

    Which means you copy (and adjust as needed) the content on that page into your docker-compose file and then start it from where you put that file.
3. Run `docker compose up -d`
4. Have a toast.

**Comment by VanTuz5** [comment]
"Error response from daemon: driver failed programming external connectivity on endpoint bitmagnet-loki (7b03e5ccb832767a5b3e484b429da49c2c64c35eebc560e4c9241f4c287035b1): Bind for 0.0.0.0:3100 failed: port is already allocated"

**Comment by NiklasBr** [comment]
> Bind for 0.0.0.0:3100 failed: port is already allocated

This likely means that you in a previous attempt started some service but never stopped it, only one service per port, so you need to stop those services first.

**Comment by VanTuz5** [comment]
I checked - this port is not occupied by anything

**Comment by NiklasBr** [comment]
Then report it as a bug to Docker.
