### ISSUE TITLE
Exact Phrase Search

### ISSUE THREAD

**Issue by 8ullyMaguire** [bitmagnet-io/bitmagnet#224]
Search for an exact sequence of words by enclosing the phrase in double quotes, e.g., `"Keyword1 keyword2"`. For instance, a search for `"kw1 kw2" kw3 kw4` would return results containing `kw1` and `kw2` together (in that order), and `kw3` and `kw4` appearing anywhere in the result.

### Related
- [Advanced Search Options](https://github.com/bitmagnet-io/bitmagnet/issues/15)
- [Scope Search to Title, Content or Both](https://github.com/bitmagnet-io/bitmagnet/issues/222)
- [Numeric Range Filters](https://github.com/bitmagnet-io/bitmagnet/issues/229)
- [Boolean Operators](https://github.com/bitmagnet-io/bitmagnet/issues/225)
- [Hash Search](https://github.com/bitmagnet-io/bitmagnet/issues/230)
- [Saved Searches](https://github.com/bitmagnet-io/bitmagnet/issues/228)
- [Regular Expression Search](https://github.com/bitmagnet-io/bitmagnet/issues/227)
- [Wildcard Matching](https://github.com/bitmagnet-io/bitmagnet/issues/226)
- [Field-Specific Search](https://github.com/bitmagnet-io/bitmagnet/issues/223)

**Comment by mgdigital** [comment]
Hi, this is already possible, please see https://bitmagnet.io/tutorials/text-search.html
