### ISSUE TITLE
Boolean Operators

### ISSUE THREAD

**Issue by 8ullyMaguire** [bitmagnet-io/bitmagnet#225]
Implement support for combining keywords with boolean operators (AND `&`, OR `|`, NOT `-`) to enable more complex search queries. This would allow users to construct intricate search expressions, improving the overall search functionality.

### Related
- [Advanced Search Options](https://github.com/bitmagnet-io/bitmagnet/issues/15)
- [Scope Search to Title, Content or Both](https://github.com/bitmagnet-io/bitmagnet/issues/222)
- [Numeric Range Filters](https://github.com/bitmagnet-io/bitmagnet/issues/229)
- [Exact Phrase Search](https://github.com/bitmagnet-io/bitmagnet/issues/224)
- [Hash Search](https://github.com/bitmagnet-io/bitmagnet/issues/230)
- [Saved Searches](https://github.com/bitmagnet-io/bitmagnet/issues/228)
- [Regular Expression Search](https://github.com/bitmagnet-io/bitmagnet/issues/227)
- [Wildcard Matching](https://github.com/bitmagnet-io/bitmagnet/issues/226)
- [Field-Specific Search](https://github.com/bitmagnet-io/bitmagnet/issues/223)

**Comment by mgdigital** [comment]
Hi, this is already possible, please see https://bitmagnet.io/tutorials/text-search.html
