### ISSUE TITLE
Wildcard Matching

### ISSUE THREAD

**Issue by 8ullyMaguire** [bitmagnet-io/bitmagnet#226]
Support the use of wildcards like `*` or `?` to match patterns (e.g., `s01ep*` to match episode numbers). This would enable users to perform more flexible searches, improving the overall search experience.

### Related
- [Advanced Search Options](https://github.com/bitmagnet-io/bitmagnet/issues/15)
- [Scope Search to Title, Content or Both](https://github.com/bitmagnet-io/bitmagnet/issues/222)
- [Numeric Range Filters](https://github.com/bitmagnet-io/bitmagnet/issues/229)
- [Exact Phrase Search](https://github.com/bitmagnet-io/bitmagnet/issues/224)
- [Boolean Operators](https://github.com/bitmagnet-io/bitmagnet/issues/225)
- [Hash Search](https://github.com/bitmagnet-io/bitmagnet/issues/230)
- [Saved Searches](https://github.com/bitmagnet-io/bitmagnet/issues/228)
- [Regular Expression Search](https://github.com/bitmagnet-io/bitmagnet/issues/227)
- [Field-Specific Search](https://github.com/bitmagnet-io/bitmagnet/issues/223)

**Comment by mgdigital** [comment]
Hi, wildcard suffixes are already possible, please see https://bitmagnet.io/tutorials/text-search.html
