### ISSUE TITLE
Hash Search

### ISSUE THREAD

**Issue by 8ullyMaguire** [bitmagnet-io/bitmagnet#230]
Implement the ability to search torrents by their hash value. Sometimes I know exactly what I'm looking for, and using a title or file name search may return multiple results. By allowing users to search directly by the hash Bitmagnet can provide a way to quickly find a single, precise result.

### Related
- [Advanced Search Options](https://github.com/bitmagnet-io/bitmagnet/issues/15)
- [Scope Search to Title, Content or Both](https://github.com/bitmagnet-io/bitmagnet/issues/222)
- [Numeric Range Filters](https://github.com/bitmagnet-io/bitmagnet/issues/229)
- [Exact Phrase Search](https://github.com/bitmagnet-io/bitmagnet/issues/224)
- [Boolean Operators](https://github.com/bitmagnet-io/bitmagnet/issues/225)
- [Saved Searches](https://github.com/bitmagnet-io/bitmagnet/issues/228)
- [Regular Expression Search](https://github.com/bitmagnet-io/bitmagnet/issues/227)
- [Wildcard Matching](https://github.com/bitmagnet-io/bitmagnet/issues/226)
- [Field-Specific Search](https://github.com/bitmagnet-io/bitmagnet/issues/223)

**Comment by 8ullyMaguire** [comment]
Yeah sorry I meant that.

**Comment by mgdigital** [comment]
Hi, search by info hash should already work
