### ISSUE TITLE
To be able to sort the torrent per size and seeders/leechers

### ISSUE THREAD

**Issue by imTHAI** [bitmagnet-io/bitmagnet#232]
Hello,

It would be nice if, once we did a search on a word, we could sort the result by size or by the number of seeders and/or leechers, by clicking on the appropriate "column" like with Finder in our computer.

**Comment by Qu4Q** [comment]
+1

**Comment by mgdigital** [comment]
This is a duplicate of https://github.com/bitmagnet-io/bitmagnet/issues/17
