### ISSUE TITLE
docker-compose error

### ISSUE THREAD

**Issue by skippa** [bitmagnet-io/bitmagnet#24]
Used git to clone dir, then ran 
`docker-compose up d`

got this error

```
ERROR: yaml.scanner.ScannerError: mapping values are not allowed here
  in "./../docker-compose.yaml", line 4, column 41
```

Not sure what I'm doing wrong...  I'm using the included example docker-compose.dev.yml file

**Comment by mgdigital** [comment]
Please do not open issues asking for general support with setting up the app and configuring Docker, as such requests are too time consuming to handle. All the information you need to get up and running is in the Bitmagnet docs, the Docker docs and on Google. If you'd like to suggest improvements or corrections to the docs then please open a PR. If you think you've found a bug then please help us out by letting us know. :heart:
