### ISSUE TITLE
WebUI enhancement

### ISSUE THREAD

**Issue by xja** [bitmagnet-io/bitmagnet#247]
- [x] I have checked the existing issues to avoid duplicates
- [x] I have redacted any info hashes and content metadata from any logs or screenshots attached to this issue

### Describe the bug

When the title is too long to show in one line, it will cause some UI issues, including:
1. Causing the sibling columns to squeeze: `Size`, `S / L`.
2. Causing the position of paginator to change.

[SCREENSHOT REDACTED DUE TO VISIBLE CONTENT METADATA]

### Environment Information (Required)

- Bitmagnet version: `[0.7.14]`
- OS and version: `Ubuntu 22.04`
- Browser and version (if issue is with WebUI): `[Firefox 124.0.2]`
- Please specify any config values for which you have overridden the defaults: none

### Suggestions
1. Consider trimming the title when it's too long, or make the rest of the columns with fixed length and position.
2. Pin the paginator at the bottom right of the results div or top right of the table, just don't scroll with the page.

**Comment by mgdigital** [comment]
This is fixed in v0.9.0
