### ISSUE TITLE
Unix socket for postgresql not supported

### ISSUE THREAD

**Issue by viraptor** [bitmagnet-io/bitmagnet#25]
I wanted to connect to local postgres using a Unix socket. Unfortunately it doesn't seem to be supported.

**Comment by mgdigital** [comment]
Thanks. I'll look at this when I can, or if you'd like to open a PR it would probably be a tweak of this file: https://github.com/bitmagnet-io/bitmagnet/blob/main/internal/database/postgres/config.go

**Comment by viraptor** [comment]
I was wrong. The socket can be used, but by pointing POSTGRES_HOST at the directory, not the socket itself.
So for example `POSTGRES_HOST=/var/run/postgresql/` works fine. Maybe worth including in the docs.

**Comment by falxie** [comment]
Seconding that documenting that the socket is supported like this would be very useful. Connecting with a socket allows for local peer based authentication
