### ISSUE TITLE
bitmagnet.exe does not start on windows

### ISSUE THREAD

**Issue by Wannacry-ops** [bitmagnet-io/bitmagnet#255]
![image](https://github.com/bitmagnet-io/bitmagnet/assets/55076853/cb044549-a7aa-4520-8ced-6d9439f0b892)

**Comment by mgdigital** [comment]
The exe is working for me. Please note bitmagnet is not a desktop app, it is a CLI - if you run it without any arguments, it will print the help message to the terminal and then exit. Please refer to the docs at https://bitmagnet.io/ for configuration and usage. You'll want to provide configuration and start the workers, e.g. with `.\bitmagnet.exe worker run --all`.

Closing for now, please let me know if you still think there's an issue.
