### ISSUE TITLE
Bootstrap nodes are hardcoded via anacrolix/dht library defaults

### ISSUE THREAD

**Issue by DegenCoden** [bitmagnet-io/bitmagnet#27]
It appears that currently, there is no way to configure bootstrap nodes, and which bootstrapping nodes are used are decided by the library anacrolix/dht: https://github.com/bitmagnet-io/bitmagnet/blob/main/internal/dht/crawler/crawl_bootstrap_hosts.go#L14

These would be the nodes used:
https://github.com/anacrolix/dht/blob/99d8ef71342b650e2cd25a0d81be8986a2e69221/dht.go#L106-L115

Being able to configure bootstrap nodes would not only be useful and provide control to the user to extend the list, it would also allow users to avoid bootstrapping with certain nodes they don't want.

**Comment by mgdigital** [comment]
Hi @DegenCoden , this is addressed in the linked PR which will be merged shortly.
