### ISSUE TITLE
You are using the default TMDB api key

### ISSUE THREAD

**Issue by warmwhisky** [bitmagnet-io/bitmagnet#28]
I have created a config.yml file and pasted in 
```yaml
tmdb:
  api_key: xxxxxxxxxxx
```

But I still get the error. Or is this expected?
` you are using the default TMDB api key; TMDB requests will be limited to 1 per second; to remove this warning please configure a personal TMDB api key`

**Comment by mgdigital** [comment]
Hi @warmwhisky , I've double checked and this works for me, which suggests your `config.yml` is in neither one of:

- the current working directory from which you're running BM
- the XDG app config directory for `bitmagnet` on your platform

If all else fails you could set it as an environment variable `TMDB_API_KEY` instead...

**Comment by warmwhisky** [comment]
Hi @mgdigital I have bitmagnet store in C:/bitmagnet with the following direcctory structure

```
C:/bitmagnet
    data (directory)
    .env
    config.yml
    docker-compose.yml
```

I have also tried using the .env file with the following in it too but I get the same error
```env
TMDB_API_KEY=xxxxxxxxxxx \
```

I guess I am not mounting the coinfig file? Do I have to add the config to the ` docker-compose.yml` file?

**Comment by mgdigital** [comment]
Yes, either that or set the env var in `docker-compose.yml`

**Comment by warmwhisky** [comment]
Unfortunelty I do not know how that is done. I guess this is why I cannot get it to work. The docs assume we know this part?

**Comment by mgdigital** [comment]
The docs are already very clear on how to do this.

**Comment by warmwhisky** [comment]
I respectfully hold a different viewpoint, which is why I took the initiative to open an issue.

**Comment by mgdigital** [comment]
Jeez, either:

- look again at my instructions above
- look again at the docs more carefully
- LOOK in your docker-compose file and see the example of how to do exactly this is already there
- Google it

This isn't the Docker support hotline (their docs are also very detailed and clear) - if you can't set an environment variable (or take the initiative to find out for yourself how to do this) you probably shouldn't be using this app. 

I'm sorry I bothered....

**Comment by warmwhisky** [comment]
> Jeez, either:
> 
> look again at my instructions above
> look again at the docs more carefully
> LOOK in your docker-compose file and see the example of how to do exactly this is already there
> Google it
> This isn't the Docker support hotline (their docs are also very detailed and clear) - if you can't set an environment variable (or take the initiative to find out for yourself how to do this) you probably shouldn't be using this app.
> 
> I'm sorry I bothered....

I think you are right. I should not be using this app.
