### ISSUE TITLE
queue jobs left staled

### ISSUE THREAD

**Issue by scratchmex** [bitmagnet-io/bitmagnet#295]
- [x] I have checked the existing issues to avoid duplicates
- [x] I have redacted any info hashes and content metadata from any logs or screenshots attached to this issue

### Describe the bug

I have a ton of pending jobs in the queue which have not been processed. I believe it's because of a problem in the design of the queue. You only listen to notifications on insert to the `queue_jobs` table but don't have any lifecycle of checking pending jobs in which the notification didn't arrive for some reason (maybe we had the workers at full and we stopped the server). The code in question is
https://github.com/bitmagnet-io/bitmagnet/blob/6cf825b907f0905100f5f9c5fd18943b26c0833b/internal/queue/server/server.go#L148-L177

I looked through the code a bit and it seems like this line should handle the cases I am referring to but for some reason it is not
https://github.com/bitmagnet-io/bitmagnet/blob/6cf825b907f0905100f5f9c5fd18943b26c0833b/internal/queue/server/server.go#L169

### To Reproduce

I don't know the cause but my believe is that somehow the notification was never received by the backend and because there is no lifecycle to check pending jobs, there were never processed

### Environment Information (Required)

- Bitmagnet version: `v0.9.4`
- OS and version: `linux`
- Browser and version (if issue is with WebUI): NA
- Please specify any config values for which you have overridden the defaults: NA

### Additional context

```
SELECT queue, status, created_at, retries, run_after, deadline, ran_at 
FROM public.queue_jobs
WHERE status = 'pending'
```
total rows: 175,572
<img width="1130" alt="image" src="https://github.com/user-attachments/assets/813425d7-f3bf-45ca-9173-7a2dbcd343f1">

**Comment by scratchmex** [comment]
@mgdigital I see you made the code for the job queue. do you have any idea what might be happening?

**Comment by mgdigital** [comment]
Hi @scratchmex , I can't see anything unusual here. You have pending jobs in your queue which is normal, and they will be processed in order of insertion once the `run_after` time is reached. If you check the `/metrics` endpoint, and see a positive number for `bitmagnet_queue_jobs_total{queue="process_torrent",status="processed"}`, and this number increases after several minutes, then everything is normal. 

> You only listen to notifications on insert to the queue_jobs table but don't have any lifecycle of checking pending jobs

This is not correct - the queue worker is constantly checking for pending jobs that are eligible to be run. 

I'm closing for now, if you still think there's an issue please could you provide more details - how many pending jobs do you have in total, is the "processed" number increasing?

**Comment by scratchmex** [comment]
There are plenty of dates 2 months old. Why are they not being processed after such a long time?

**Comment by mgdigital** [comment]
What do you have for the metric `bitmagnet_queue_jobs_total{queue="process_torrent",status="processed"}`, and is the number increasing? Do you definitely have the queue worker running, and do you see recent "processed" jobs in the database?

**Comment by scratchmex** [comment]
I see recent processed jobs in the database, only very recent

**Comment by mgdigital** [comment]
You have an unusually high number of jobs in your queue - did you maybe run `bitmagnet reprocess` several times? The jobs inserted by the crawler have a higher priority than those inserted by `bitmagnet reprocess`, so they will run first. It may take some time for it to work through those hundreds of thousands backed up. I'd suggest clearing the queue_jobs table and then running the following to process any torrents that still need to be:

```sh
bitmagnet reprocess --apisDisabled --localSearchDisabled --orphans
```

**Comment by scratchmex** [comment]
I have not run `bitmagnet reprocess`
```sql
SELECT queue, status, created_at, priority 
FROM public.queue_jobs
WHERE status = 'pending'
ORDER BY created_at
```
<img width="576" alt="image" src="https://github.com/user-attachments/assets/eb895589-d8c8-4919-8dbd-bc47793cc0b3">

Could it be that the processing is throttled by the TMDB API?

Just ran your suggestion. Just curious, this doesn't mean I lost some torrents found in the DHT, right?

**Comment by mgdigital** [comment]
> Could it be that the processing is throttled by the TMDB API?

The crawler-inserted jobs will run much faster if you either get a personal TMDB API key, or disable TMDB. If you have millions of torrents it is fairly essential to do this.

>  this doesn't mean I lost some torrents found in the DHT, right?

No nothing will be lost.

**Comment by scratchmex** [comment]
I am now seeing new torrents in the UI. Before it was stuck on 2 months ago.. now 1 minute ago. So it seems like a bug, right? Why wasn't processing torrents before?

**Comment by mgdigital** [comment]
> So it seems like a bug, right?

If jobs are being added faster than they are being processed then over time you will end up with lots of old jobs in the queue. It's not exactly a bug, but better visibility and management of the queue are being worked on. I've just pushed a small update in 0.9.5 which should improve the queue throughput when using the default TMDB API key.
