### ISSUE TITLE
The command to run the server is ./bitmagnet worker  run --all=true

### ISSUE THREAD

**Issue by benjistokman** [bitmagnet-io/bitmagnet#312]
- [X] I have checked the existing issues to avoid duplicates
- [X] I have redacted any info hashes and content metadata from any logs or screenshots attached to this issue

### Is your feature request related to a problem? Please describe

Please just add this somewhere. The entirety of the documentation for this application just says "go read -h" and -h doesn't help one bit.

### Describe the solution you'd like

Make some documentation or something.

### Describe alternatives you've considered

Run this action by default (with just "./bitmagnet")

### Additional context

Docker was complaining about not having protocol http+docker so... IDK. Docker doesn't work as well as most people think it does.

**Comment by mgdigital** [comment]
Added in https://github.com/bitmagnet-io/bitmagnet/pull/280
