### ISSUE TITLE
does this app hide or remove any torrent by default?

### ISSUE THREAD

**Issue by rezad1393** [bitmagnet-io/bitmagnet#331]
- [ x] I have checked the existing issues to avoid duplicates
- [ x] I have redacted any info hashes and content metadata from any logs or screenshots attached to this issue

this is not a bug just a question.

does this app remove or hide any content by default?
do I have to do something to hide porn or illegal content (like csam) or is it done by default?

because in the docker-compose.yml I see no keywork for banning stuff.

can someone explain this to me?

**Comment by denniskrol** [comment]
> illegal content (like csam) or is it done by default?
By default: https://bitmagnet.io/guides/classifier.html#auto-delete-torrents-containing-specific-keywords

**Comment by rezad1393** [comment]
> > illegal content (like csam) or is it done by default?
> 
> By default: https://bitmagnet.io/guides/classifier.html#auto-delete-torrents-containing-specific-keywords

how do I add or remove from this list?

**Comment by mgdigital** [comment]
> how do I add or remove from this list?
> where can I see the list of default words?

All that is explained in the page you just linked to :)

**Comment by rezad1393** [comment]
> > how do I add or remove from this list?
> > where can I see the list of default words?
> 
> All that is explained in the page you just linked to :)

it has a guide for adding words to categories and banned words.
but I want to remove words from categories and banned groups.

**Comment by mgdigital** [comment]
> but I want to remove words from categories and banned groups.

The only reason you'd need to do this is for indexing CSAM. This is not a common use case and the only way to do this is to overwrite the default classifier completely.

**Comment by rezad1393** [comment]
> > but I want to remove words from categories and banned groups.
> 
> The only reason you'd need to do this is for indexing CSAM. This is not a common use case and the only way to do this is to overwrite the core classifier completely - that's also explained in the docs.

???
I want to move a word from one catogory to another?
what that has got to do with csam?

**Comment by mgdigital** [comment]
Explain what you're trying to do - you can already add keywords to any list.

**Comment by rezad1393** [comment]
> Explain what you're trying to do - you can already add keywords to any list.

create a new catogories and move some of the keyworks to them that are already in movies and ebooks.

**Comment by mgdigital** [comment]
> create a new catogories 
> like a DVD-R cat and sepeare ebook cat for pdf?

Only the existing core categories exist and these can't be added to, but you can add any tag you like to create a custom "category". You can also use the file type filter or the search facility to find PDF files within an existing category.

**Comment by rezad1393** [comment]
> > create a new catogories
> > like a DVD-R cat and sepeare ebook cat for pdf?
> 
> Only the existing core categories exist and these can't be added to, but you can add any tag you like to create a custom "category". You can also use the file type filter or the search facility to find PDF files within an existing category.

so I cant "move" a tag to another new cat?

**Comment by mgdigital** [comment]
> so I cant "move" a tag to another new cat?
New categories aren't possible - that's what tags are for.

**Comment by rezad1393** [comment]
> > create a new catogories
> > like a DVD-R cat and sepeare ebook cat for pdf?
> 
> Only the existing core categories exist and these can't be added to, but you can add any tag you like to create a custom "category". You can also use the file type filter or the search facility to find PDF files within an existing category.

I want to be able to separate some stuff from the rest (not duplicated in other catogories)
the most important for me is compressed stuff and specific ebook types.

it I add a "new" cat with for example sub tag of pdf, do my already indexed torrent go to that ? or only new torrents?

**Comment by rezad1393** [comment]
> > so I cant "move" a tag to another new cat?
> 
> New categories aren't possible - that's what tags are for.

oh.
ok.
thanks for the answers and sorry if I asked a lot.
I am trying to fine tune this app.

**Comment by mgdigital** [comment]
> it I add a "new" cat with for example sub tag of pdf, do my already indexed torrent go to that ? or only new torrents?

You'd need to reprocess the already existing torrents to get the tag added: https://bitmagnet.io/guides/reprocess-reclassify.html

**Comment by rezad1393** [comment]
> > it I add a "new" cat with for example sub tag of pdf, do my already indexed torrent go to that ? or only new torrents?
> 
> You'd need to reprocess the already existing torrents to get the tag added: https://bitmagnet.io/guides/reprocess-reclassify.html

thanks!!
