### ISSUE TITLE
Non-utf8 string in "error creating torrent model"

### ISSUE THREAD

**Issue by viraptor** [bitmagnet-io/bitmagnet#37]
**Have you checked the roadmap on the website, and existing issues, before opening a dupllcate issue?**
Yes

**Describe the bug**

Occasionally this fails with a stacktrace.

```
ERROR   dht_staging     staging/staging.go:301  error creating torrent model: invalid utf8 string
github.com/bitmagnet-io/bitmagnet/internal/dht/staging.(*staging).Respond
        github.com/bitmagnet-io/bitmagnet/internal/dht/staging/staging.go:301
github.com/bitmagnet-io/bitmagnet/internal/dht/crawler.(*crawler).handleStagingRequest.func1
        github.com/bitmagnet-io/bitmagnet/internal/dht/crawler/handle_staging_request.go:40
github.com/bitmagnet-io/bitmagnet/internal/dht/crawler.(*crawler).handleStagingRequest
        github.com/bitmagnet-io/bitmagnet/internal/dht/crawler/handle_staging_request.go:77
```

**To Reproduce**

Unknown

**Expected behavior**

This error appears without any context.
If this is something that the operator can fix, the error should contain enough context to do that.
If this is a problem with an incoming packet that happens to have non-utf8 strings and can't be fixed, then maybe it can be degraded to a DEBUG/INFO without a stacktrace.

**General (please complete the following information):**

- Bitmagnet version: 0.0.7
- OS and version: nixos
- Browser and version (if issue is with WebUI):

**Comment by mgdigital** [comment]
Hi @viraptor , that error simply means one of the meta infos we found was malformed and so we discarded it. The log entry needs downgrading to debug level.

**Comment by mgdigital** [comment]
Hi @viraptor , this is fixed in the linked PR which will be merged shortly.
