### ISSUE TITLE
High memory growth over time

### ISSUE THREAD

**Issue by viraptor** [bitmagnet-io/bitmagnet#39]
**Have you checked the roadmap on the website, and existing issues, before opening a dupllcate issue?**
Yes

**Describe the bug**
There seems to be a memory leak / unconstrained growth. The process seems to gain ~a couple hundred MB of used memory every day.

**To Reproduce**

1. Run the app
2. Index ~150k entries over 3 days
3. App takes >1GB of memory

**Expected behavior**
App takes close to the initial size, or has a configuration option that sets the high bound for caches.

**General (please complete the following information):**

- Bitmagnet version: 0.0.7
- OS and version: nixos

I'm happy to provide more info if there's a good way to get some more detailed numbers out of the app.

**Comment by mgdigital** [comment]
Thanks. There's currently a complete rewrite of the DHT crawler happening - the present implementation is rather spaghettified and also non compliant with DHT standards (see the other issue on this). So there's probably not much point trying to track this down right now but let's see where we are when that's done...

**Comment by mgdigital** [comment]
Hi @viraptor , I believe this is fixed in the linked PR which will be merged shortly. For me memory usage is remaining below ~200MB with the default configuration.

**Comment by viraptor** [comment]
357MB with ~600k entries indexed, but seems to be holding steady. I'll report back if things change.

On another positive note, the CPU usage is WAY lower now.

**Comment by Giggitybyte** [comment]
grateful for the fixes!

**Comment by mgdigital** [comment]
Thanks for confirming @viraptor - I wonder what causes the memory difference - different hardware perhaps; I don't think total indexed entries should affect memory usage. If it's holding steady then that's the main thing...

I'm also curious what throughput people are getting from the crawler as I get dramatically different results on similar hardware (though universally better than the previous version).

So for example:

```sql
select count(*),
       extract(year from created_at) as year,
       extract(month from created_at) as month,
       extract(day from created_at) as day,
       extract(hour from created_at) as hour
from torrents
group by year, month, day, hour
order by year desc, month desc, day desc, hour desc
limit 100
```

This tells me I'm crawling 5-7k per hour on my M2 Mac Mini but more like 30k per hour on my M2 MacBook Air which is a bit weird. One of the next steps will be to add some telemetry to the different pipeline stages of the crawler so I can understand better where the bottlenecks are.

BTW I have set up a Discord that you're welcome to join, I'll put it on the website in due course but it's here: https://discord.gg/WecPrUFr (cc @Giggitybyte )

**Comment by viraptor** [comment]
In terms of BW, ~2-4Mibps down.

```
 count | year | month | day | hour 
-------+------+-------+-----+------
  5349 | 2023 |    11 |   8 |   10
 11594 | 2023 |    11 |   8 |    9
  9079 | 2023 |    11 |   8 |    8
 12309 | 2023 |    11 |   8 |    7
  4052 | 2023 |    11 |   8 |    6
  9241 | 2023 |    11 |   8 |    5
  8892 | 2023 |    11 |   8 |    4
 14505 | 2023 |    11 |   8 |    3
 11609 | 2023 |    11 |   8 |    2
 13393 | 2023 |    11 |   8 |    1
 11591 | 2023 |    11 |   8 |    0
```

So averaging 10k or so per hour on a [2013-era underpowered intel](https://ark.intel.com/content/www/us/en/ark/products/75028/intel-core-i5-4250u-processor-3m-cache-up-to-2-60-ghz.html).

**Comment by leofidus** [comment]
> This tells me I'm crawling 5-7k per hour on my M2 Mac Mini but more like 30k per hour on my M2 MacBook Air which is a bit weird. One of the next steps will be to add some telemetry to the different pipeline stages of the crawler so I can understand better where the bottlenecks are.

I'll make an issue once I've understood the problem well enough to actually describe it, but with the new version my crawling rate craters after a couple hours due to what appears to be some sort of network-related problem (as in it gets in a state where TCP latency shoots up drastically). So based on very little my guess would be that your Mac Mini and your MacBook Air might be on the network layer.

**Comment by mgdigital** [comment]
> my crawling rate craters after a couple hours due to what appears to be some sort of network-related problem (as in it gets in a state where TCP latency shoots up drastically)

Thanks @leofidus , let me know your findings - I've not seen this happen myself. Weird that it only happens with the new version, especially as the old version had a TCP connection leak bug (https://github.com/bitmagnet-io/bitmagnet/issues/42)

**Comment by leofidus** [comment]
Looks like my issue was related to a piece of network gear not being able to keep up. I've set `DHT_CRAWLER_SCALING_FACTOR=1` and now have a stable connection, with about 10k torrents/hour, at about 4Mbps down, 2 Mbps up (though the down rate is really fluctuation between 1.5Mbps and 13Mbps at a relatively stable 500-800 pps, according to iptraf-ng). Memory usage is about 130MB for the bitmagnet docker container.

**Comment by mgdigital** [comment]
Thanks @leofidus , that's interesting - I might have set the default for that a bit too high then.

So (in case you hadn't seen) we have all these buffered channels and semaphores in the crawler pipeline: https://github.com/bitmagnet-io/bitmagnet/blob/main/internal/dhtcrawler/crawler.go#L56

The optimal values for these might depend on any number of factors, I thought it would be too much to expose these all as configurable, hence the scaling factor. I haven't done a lot of experimenting with these or been able to compare results with a wide variety of hardware/network conditions....

**Comment by viraptor** [comment]
If you expose the runtime metrics in some way like https://github.com/mmcshane/salp or https://prometheus.io/docs/guides/go-application/ I'm happy to report how things are working in a couple environments.

**Comment by mgdigital** [comment]
Hi @viraptor , there's some basic info available on the `bitmagnet:3333/status` endpoint.

There is also a Gops agent running in the app: https://github.com/google/gops If you mount a local directory to `/tmp` in the container you can do things like `docker exec bitmagnet gops pprof-heap 1` or `docker exec bitmagnet gops pprof-cpu 1` and look at the output file with `go tool pprof`; I think this can also link to things like Prometheus but I'm not too experienced with this...

I'm intending to add some better telemetry solution but need to look at the options, I was thinking possibly https://opentelemetry.io/docs/instrumentation/go/

**Comment by viraptor** [comment]
opentelemetry sounds great too 👍
