### ISSUE TITLE
Running for a long time causes socket fd leak

### ISSUE THREAD

**Issue by NeoChen1024** [bitmagnet-io/bitmagnet#42]
**Have you checked the roadmap on the website, and existing issues, before opening a dupllcate issue?**
Yes

**Describe the bug**
After running for a while, the "closed" TCP connection count only goes up, until I manually restart the docker container which bitmagnet is running inside. (could be over 10k after a few hours)
![ss -s status](https://github.com/bitmagnet-io/bitmagnet/assets/25676597/7c507c28-da63-4ba1-bdb9-dcef8ddf0ed8)

**To Reproduce**
1. Run it long enough

**Expected behavior**
"closed" TCP connection count remain low.

**General (please complete the following information):**

- Bitmagnet version: 0.0.7
- OS and version: Arch Linux (kernel 6.1.59)
- Browser and version (if issue is with WebUI): Firefox 118.02

**Additional context**
None

**Comment by NeoChen1024** [comment]
After left running for a night:
![screenshot of ss -s](https://github.com/bitmagnet-io/bitmagnet/assets/25676597/87e27566-5243-42a0-88d1-1b0cbac7e343)

**Comment by mgdigital** [comment]
Hi @NeoChen1024 , I believe this is fixed in the linked PR which will be merged shortly.
