### ISSUE TITLE
dht_crawler.save_pieces configuration option is ignored.

### ISSUE THREAD

**Issue by Send8213** [bitmagnet-io/bitmagnet#59]
**Have you checked the roadmap on the website, and existing issues, before opening a duplicate issue?**
Yes

**Describe the bug**
dht_crawler.save_pieces configuration option is ignored. It looks like it is not referenced at all in persist.go's createTorrentModel function, while the the other space-saving option dht_crawler.save_files_threshold is referenced and respected. This causes the database to grow in size quite a bit faster than before.

**To Reproduce**

1. Setup bitmagnet from docker
2. Use the default configuration option for dht_crawler.save_pieces: false or set the option manually.
3. Check the pieces and piece_length columns in torrents table of the database as things are crawled and see that they are not null.
4. Watch the database expand as it fills with pieces data

**Expected behavior**
By default, pieces and piece_length should not be saved and should be null in the database.

**General (please complete the following information):**

- Bitmagnet version: v0.1.0 (v0.0.7 seems unaffected)
- OS and version: Fedora 39
- Browser and version (if issue is with WebUI): N/A

**Additional context**

**Comment by hunmar** [comment]
Same problem with overgrowing DB
Did you find a temporary solution for this?

**Comment by mgdigital** [comment]
Ah thanks - that was a bit of an oversight! Just about to release a fix for this. To recover the used space you'll need to do:

```sql
update torrents set pieces = null, piece_length = null where pieces is not null;
```

(this may take a few minutes)
