### ISSUE TITLE
Loved the project, any public place where its hosted

### ISSUE THREAD

**Issue by the-rarbg** [bitmagnet-io/bitmagnet#66]
hi i loved the project, just wanna ask if its hosted anywhere publically.

**Comment by kodxana** [comment]
I think this project was more made to be for private usage rather than public instances.

**Comment by the-rarbg** [comment]
yes but for people who want to try it before using it or are not tech savy, or who dont have much bandwidth that could be useful

**Comment by Giggitybyte** [comment]
I doubt that this project will ever have a public instance; I feel the whole point of the project is to encourage decentralization. 
I also currently don't have much bandwidth, so for me what I did to test the project out was rent a cheap VPS from [OVH](https://us.ovhcloud.com/) with symmetrical 500 Mbit up/down and unlimited transfer. I'd recommend going that route if you've got a little cash to spare.

Using docker compose is pretty simple once you have it installed; most projects can be ran using just a text file and one command.
Check out these links.
https://docs.docker.com/compose/install/linux/#install-using-the-repository
https://bitmagnet.io/setup/installation.html#docker

**Comment by the-rarbg** [comment]
yeah to much bandwidth is taken, but i have some spare bandwidth, if  #70 is done i could put it in an instance, any thought?

**Comment by mgdigital** [comment]
People are welcome to host public instances or build their own apps on top of the API, but it isn't something this project will ever be involved with directly. This is alpha software right now and hasn't had any kind of security or scalability review, so it would probably not be advisable for people to try it at this stage.

The primary focus will always be self hosting and providing an alternative to the ad-plastered public websites that can disappear at any time. I'm more interested in allowing instances to federate and encouraging decentralisation, than having this used for the next public website - I'm not against providing tools that people can build anything they want on top of though.
