### ISSUE TITLE
Ability to configure displayed content types

### ISSUE THREAD

**Issue by kodxana** [bitmagnet-io/bitmagnet#68]
**Have you checked the roadmap on the website, and existing issues, before opening a dupllcate issue?**
Yes

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Give option to fully hide XXX section from the web ui either by setting env variable in docker-compose or switch from web UI

**Describe alternatives you've considered**

**Additional context**
I'm not fan of XXX content and when running on cloud provider do not want store or see this kinda of content would be great if XXX content could be disable from showing on UI side.

**Comment by mgdigital** [comment]
It is a priority to add this sort of functionality. Your only option right now is acting directly on the database. Best to delete from the `torrents` table which will cascade to all other tables, e.g. `delete from torrents where name like '%xxx%';` should get rid of a lot of it.

> Give option to fully hide XXX section from the web ui 

It's on the roadmap to allow this kind of customisation. At the moment there wouldn't be much point in hiding the XXX section as we're not yet classifying most XXX content, so you'd still be drowning in XXX in the "Unknown" section. So improving the classification is the first priority.

**Comment by mgdigital** [comment]
See my comment here: https://github.com/bitmagnet-io/bitmagnet/issues/70#issuecomment-1832682032

I'm renaming both these issues to cover the outstanding functionality.
