### ISSUE TITLE
Rule-based deletion

### ISSUE THREAD

**Issue by the-rarbg** [bitmagnet-io/bitmagnet#70]
many torrents but would be a great addition to project if we could pass a flag to only store data or torrents that are categorized and  not store unknown ones

**Comment by the-rarbg** [comment]
@mgdigital can we have a flag like  --keys=http_server --keys=queue_server for this

**Comment by mgdigital** [comment]
Giving a similar answer as was given on https://github.com/bitmagnet-io/bitmagnet/issues/68:

It is a priority to add this sort of functionality. Your only option right now is acting directly on the database e.g. (example I gave for removing the porn) `delete from torrents where name like '%xxx%';` - or join onto the torrent_contents table to locate and delete unclassified content (but always delete from the `torrents` table which will cascade to all other tables).

**Comment by kodxana** [comment]
Most issue is that deleting stuff from database do not prevents crawler of getting that data back again.

**Comment by mgdigital** [comment]
> deleting stuff from database do not prevents crawler of getting that data back again

Correct. The complete solution will probably involve a bloom filter to avoid re-crawling content you don't want. From the roadmap:

> Smart deletion: there’s a lot of crap out there; crawling DHT can quickly use lots of database disk space, and search becomes slower with millions of indexed torrents of which 90% are of no interest. A smart deletion feature would use saved searches to identify content that you’re not interested in, including low quality content (such as low resolution movies). It would automatically delete associated metadata and add the info hash to a bloom filter, preventing the torrent from being re-indexed in future.

**Comment by kodxana** [comment]
In theory we could still store just info hash into blacklist though do not pull rich metadata to it.

**Comment by mgdigital** [comment]
> we could still store just info hash into blacklist

We could, but this list might get very big, so it's probably better to use a bloom filter instead of storing every "deleted" hash.

**Comment by leofidus** [comment]
Storing every blacklisted hash would still be strictly less space than not doing the filtering at all and storing all metadata. So even that version would still be useful. But I agree that this might be a good use case for a bloom filter.

**Comment by mgdigital** [comment]
> Storing every blacklisted hash would still be strictly less space than not doing the filtering at all and storing all metadata

What I envisage is having multiple separate lists / bloom filters, e.g. hashes I manually deleted; hashes that failed a rule I configured (and in future I might want to edit or disable this rule and clear the filter independently of others); hashes that were detected to be CSAM and we don't ever want to request the meta info again or store any data about them. 

This is where it gets really impractical to actually store all the hashes you're not interested in for one reason or another. If it was a bloom filter it could even be easily shared between users; my only concern would be false positives though you can make those very unlikely but not impossible.

**Comment by mgdigital** [comment]
I'm renaming this issue and this other one which is sort-of related: https://github.com/bitmagnet-io/bitmagnet/issues/68

Deleting is now possible through the UI and API. It's not exactly convenient to delete in bulk yet, you'd have to either do it 250 at-a-time in the UI or write a script to do it via the API.

Deleting through the UI/API adds the deleted hashes to a stable bloom filter which is stored in the database and **probably** stops the torrent being crawled again (see https://www.vldb.org/pvldb/vol13/p2355-liu.pdf). The basic characteristics of the filter which I think are fairly acceptable are:

- The stable bloom filter can be encoded to 25MB
- At a stable state the the false negative rate averages 1.7437% for the last million deleted torrents
- At a stable state the false positive rate is 0.09023%

So the remaining bit of this feature would be automatic rules-based deletion which would also add deleted items to the filter.

**Comment by tleydxdy** [comment]
I wonder how big the list of blocked hashes would be. If someone is willing to spend the disk space and avoid false positives then using radix search for the blocked hash list should still be fairly performant.

**Comment by nodiscc** [comment]
> Deleting is now possible through the API

Is there an example of how to achieve this through the API? I think it should be documented.

For example, I would like to remove all torrents that were classified as `XXX` by the automatic classifier (and add their hashes to the filter).

**Comment by lunks** [comment]
Hey, sorry for bringing this topic from the dead, but it's still not clear to me how can I prevent unclassified torrents to be automatically deleted like OP asked. How can I do it?

**Comment by pagdot** [comment]
Please read https://bitmagnet.io/guides/classifier.html#auto-delete-specific-content-types . I'm pretty sure you could do it with content type `unknown`

**Comment by mgdigital** [comment]
> Please read https://bitmagnet.io/guides/classifier.html#auto-delete-specific-content-types . I'm pretty sure you could do it with content type `unknown`
> 
> Also I'd recommend to go to discord for support: https://discord.gg/6mFNszX8qM

This is the correct answer, I wouldn't recommend deleting all unknown stuff but that's a separate discussion....
