### ISSUE TITLE
Docker-compose is not working out of the box: FATAL error.

### ISSUE THREAD

**Issue by tiritibambix** [bitmagnet-io/bitmagnet#71]
I tried the provided docker-compose and changed the minimum : db password, and ./data/postgres and ./data/redis, paths.

Postgres is giving me endless `FATAL:  no pg_hba.conf entry for host "192.168.176.4", user "postgres", database "bitmagnet", no encryption`

I found nothing about this issue in the docs or Google.

Any guidance would really be appreciated.

**Comment by mgdigital** [comment]
Hi, the example docker-compose is working. My only advice is to try without changing the paths or password, but sorry GitHub issues is not the place to troubleshoot this:

Please do not open issues asking for general support with setting up the app and configuring Docker, as such requests are too time consuming to handle. All the information you need to get up and running is in the Bitmagnet docs, the Docker docs and on Google. If you'd like to suggest improvements or corrections to the docs then please open a PR. If you think you've found a bug then please help us out by letting us know. :heart:
