### ISSUE TITLE
Add version number to web page

### ISSUE THREAD

**Issue by uninvitedguest** [bitmagnet-io/bitmagnet#81]
**Have you checked the roadmap on the website, and existing issues, before opening a dupllcate issue?**
Yes

**Is your feature request related to a problem? Please describe.**
It's not easy to determine the version of Bitmagnet that is currently running.

**Describe the solution you'd like**
A version number displayed on the Bitmagnet page - in the menu, along the title bar, bottom left corner, wherever.

**Comment by Send8213** [comment]
If you need to find it currently, it is at /status .

**Comment by uninvitedguest** [comment]
Thanks for te speedy reply @Send8213

**Comment by mgdigital** [comment]
Fixed in https://github.com/bitmagnet-io/bitmagnet/releases/tag/v0.7.10
