### ISSUE TITLE
Removing the `LIKE` part of the search query and normalising unicode characters

### ISSUE THREAD

**Issue by mgdigital** [bitmagnet-io/bitmagnet#89]
**Describe the bug**
Searching with a query string is slow when there are many indexed torrents.

Currently search queries get transformed to 3 conditions like this:

```sql
tsv @@ plainto_tsquery('simple', normalized_input)
tsv @@ websearch_to_tsquery('simple', normalized_input)
search_string LIKE raw_input
```

This is obviously not great and the only reason it's like this is I didn't get round to addressing this before releasing the first alpha, and it works fairly acceptably until you've got a few million torrents indexed...

The reason for the LIKE element is that `to_tsvector('simple', search_string)` was discarding unicode characters, breaking search in Asian and other unicode languages. It turns out Postgres doesn't offer a good way to convert a string to a tsvector that works well for all languages. Unfortunately the LIKE element of the query is by far the slowest.

**Proposed solution**
My proposed solution is to normalise all unicode characters within search strings and input query strings, using a library such as https://github.com/mozillazg/go-unidecode; we'll then have no unicode chars in the `search_string` or `tsv` fields, and the LIKE query can be removed, along with the supporting GIST index.

With this done, there'll need to be an easy way of running a one-time job to update the `search_string` fields with the new normalised string. A one-time job to reclassify everything should do the trick (though as a separate issue we also need a way to manually trigger a bulk reclassify)...

**Comment by claabs** [comment]
I was curious how this approach would deal with Japanese where a sentence has no spaces. I messed around with Google Translate, Unidecode, and Postgres:

English: "yesterday i took a trip to the store and purchased a sandwich"
Japanese: "昨日お店に行ってサンドイッチを購入しました"
Romanji: "Kinō o-ten ni itte sandoitchi o kōnyū shimashita"
Unidecode: "Zuo Ri oDian niXing tsutesandoitsuchiwoGou Ru shimashita"

```sql
-- Simple TSV failed to vector previously
SELECT to_tsvector('simple', '昨日お店に行ってサンドイッチを購入しました');
-- '昨日お店に行ってサンドイッチを購入しました':1

-- Improved vectors with Unidecode
SELECT to_tsvector('simple', 'Zuo Ri oDian niXing tsutesandoitsuchiwoGou Ru shimashita');
-- 'nixing':4 'odian':3 'ri':2 'ru':6 'shimashita':7 'tsutesandoitsuchiwogou':5 'zuo':1
```

Pretty promising. The only concern for this case is the huge "tsutesandoitsuchiwoGou" which is too unique for a TSV search, but I doubt we'll see many non-separated Japanese strings we will get with bitmagnet's use-case.

**Comment by mgdigital** [comment]
I've made an important realisation thanks to your comment @claabs - I've been developing against a DB set up in the Postgres for Mac app (not the Docker image) and have only just noticed this gives me different results for to_tsvector:

```
SELECT to_tsvector('simple', 'Some Chinese text: 我是中国人。');
-- Result from my Postgres for Mac app:
-- 'chinese':2 'some':1 'text':3
-- vs result from Docker Postgres:
-- 'chinese':2 'some':1 'text':3 '我是中国人':4
```

Which is why I said above about unicode chars being discarded. There's clearly a different locale or collation setting somewhere (still getting my head around how this works). So sorry my previous comments about unicode chars might not make sense without that bit of context!

So anyway, even with the CJK characters getting included in the TSV, I still think unidecode is a worthwhile normalisation step. As you pointed out the tokenisation is a bit problematic for Japanese, but this is a bit of an edge case with contiguous Katakana words. Your example sentence is getting split up a bit, which is better than nothing. As far as I can tell there are no other languages that suffer from this problem, which can possibly be addressed as a separate issue using something like https://github.com/ikawaha/kagome - I think I'd need a native speaker's opinion on how much of a problem this really is though. Chinese is getting correctly tokenised, and you also get some useful normalisations for European accented words, e.g. `hôtel` -> `hotel`, `Straße` -> `Strasse`.

So the LIKE query can be removed; that leaves the question of how to handle the rest of the query string. I think we should probably lose the `plainto_tsquery` element too. That leaves the `websearch_to_tsquery`: at the moment I'm heavily normalising the query string before passing it to `websearch_to_tsquery` (stripping out punctuation etc). That was probably a mistake on my part. If we preserve punctuation then that unlocks some advanced search capability (see the docs here https://www.postgresql.org/docs/current/textsearch-controls.html#TEXTSEARCH-PARSING-QUERIES).

**Comment by mgdigital** [comment]
At the moment the `torrent_contents.search_string` field is created as follows:

When a new torrent is added to the database, if there are no `torrent_contents` records specified a minimal one will be created in this event hook with `search_string` based on the name: https://github.com/bitmagnet-io/bitmagnet/blob/v0.3.1/internal/model/torrents.go#L26

Then if the video classifier is successful it updates the `search_string` with additional parts here: https://github.com/bitmagnet-io/bitmagnet/blob/v0.3.1/internal/classifier/video/resolver.go#L124

We probably want to rework this so the string can be generated ad-hoc/independent of the classifier.

So maybe in this file: https://github.com/bitmagnet-io/bitmagnet/blob/v0.3.1/internal/model/torrent_contents.go

We have a function:

```go
func (tc *TorrentContent) UpdateSearchString() error {
  // check we've got access to all the associated records needed:
  if tc.ContentID.Valid && tc.Content.ID != tc.ContentID.String {
    return errors.New("Missing Content record")
  }
  if tc.Torrent.InfoHash != tc.InfoHash {
    return errors.New("Missing Torrent record")
  }
  var searchStringParts []string
  // add all searchable parts applying deunicode and any other applicable normalisation
  tc.SearchString = strings.Join(searchStringParts, " ")
  return nil
}
```

After that we'll probably need a new message type for the queue so the field can be updated whenever this implementation changes.

Same as all the above applies to the `content.search_string` field which is used by the classifier and probably by other stuff in future. They share a lot of the same logic in the search engine too so the more similar they can be kept in how they work the better....
