### ISSUE TITLE
Blanked out page buttons webui v0.4.1

### ISSUE THREAD

**Issue by Red-Skuller** [bitmagnet-io/bitmagnet#94]
Can't move through the torrent pages. It only shows the first page. I can change the number of torrents displayed on a page but can't advance. It also shows the number of torrents as 0 however i have north of 2.800.000 torrents

**To Reproduce**

1. Start minimal docker-compose.yml
2. Try to change torrent page

**Expected behavior**
Supposed to change the torrent page for example from 1-10 to 11-20

**General (please complete the following information):**

- Bitmagnet version: 0.4.1
- OS and version: Linux
- Browser and version: Brave browser 1:1.61.109-1

**Additional context**

Upgraded from v0.3.1

**Comment by mgdigital** [comment]
Hi, can you confirm if the problem persists after 10 minutes (the totals should be refreshed every 10 mins)? Did the issue occur immediately after starting the container (that might be before the background job has calculated the counts)? Do you see any errors in the logs?

**Comment by Red-Skuller** [comment]
You are right. This did occur right after starting the container. After some time the numbers returned and so did the page buttons.

**Comment by Red-Skuller** [comment]
Now after 16 hours of uptime the number disappeared again and so did the page buttons. After waiting for another 30 mins they reappeared again
from docker logs bitmagnet:
i only see some UTF-8 encoding errors:
ERROR    gorm    gorm/logger.go:72       gorm trace      {"location": "/build/internal/database/dao/torrents.gen.go:616", "error": "ERROR: invalid byte sequence for encoding \"UTF8\": 0x00 (SQLSTATE 22021)", "elapsed": 32018.64195, "sql": "INSERT INTO \"torrents\" 
 ......
 DO UPDATE SET \"name\"=\"excluded\".\"name\",\"files_status\"=\"excluded\".\"files_status\",\"piece_length\"=\"excluded\".\"piece_length\",\"pieces\"=\"excluded\".\"pieces\"", "rows": 71}
 ERROR   dht_crawler     dhtcrawler/persist.go:44        error persisting torrents: ERROR: invalid byte sequence for encoding "UTF8": 0x00 (SQLSTATE 22021)
 
 Other containers have no discernible errors

**Comment by Red-Skuller** [comment]
I figured out that if i do two searches at once and close both tabs this happens
