### ISSUE TITLE
Inquiry About Directing Multiple DHT Crawlers to a Single Database

### ISSUE THREAD

**Issue by cnZary** [bitmagnet-io/bitmagnet#95]
I am considering directing multiple DHT crawlers towards a single database. My primary concern is whether this setup might result in identical data entries being repeatedly written to the database. Additionally, I am curious if there might be other potential issues that could arise from such a configuration.

**Comment by mgdigital** [comment]
Hi, this should work but will obviously put more load on the database which might slow down the API and Web UI. It shouldn't cause any data issues.
