### ISSUE TITLE
Question about import

### ISSUE THREAD

**Issue by PaoloPapao** [bitmagnet-io/bitmagnet#97]
Hi and thanks for your tool,
At the moment, i've a huge magnetico DB, is it possible to import it correctly in bitmagner please?
It would help to keep all archived magnet, thanks.

**Comment by mgdigital** [comment]
Hi, you could use the import endpoint: https://bitmagnet.io/tutorials/importing.html
However there isn't currently a way to import the data including file info, you'd only have the magnet links, torrent names and size...

**Comment by DyonR** [comment]
Replying on this closed issue in case others come across this.  
I've made a python script that reads a magnetico database and uses bitmagnet's import endpoint to import the data in to.  
https://github.com/DyonR/magnetico2bitmagnet  
Note that the import is still only limited to magnet links, torrent names and size.
